erDiagram
    Movie ||--|{ HasGenre : "has"
    Genre ||--|{ HasGenre : "belongs_to"
    User ||--|{ Rating : "rates"
    Movie ||--|{ Rating : "is_rated"
    
    User ||--|{ UserGenreRating : "has"
    Genre ||--|{ UserGenreRating : "evaluates"

    User {
        int userId PK
        string userName 
        string email  
        string password
        int age 
    }

    Genre {
        int genreID PK
        string genreName "NOT NULL"
    }

    Movie {
        int movieID PK
        string movieName "NOT NULL" 
        Date releaseDate "NOT NULL"
    }



    HasGenre {
        int movieID FK
        int genreID FK
    }

    Rating {
        int userID FK
        int movieID FK
        int rating "CHECK (rating >= 1 AND rating <= 5)"
        date timestamp "NOT NULL"
    }

    UserGenreRating {
        int genreID FK
        int userID FK
        decimal avgRating "CHECK (avgRating >= 0 AND avgRating <= 5)"
    }

